# Name
REPO_NAME           ?= YST

# File name of *.grf, *.tar and so on
BASE_FILENAME       ?= YST

# Versin
VERSION             ?= $(shell date +"%Y.%m.%d")
RECENT_UPDATED      ?= $(shell date +"%Y.%m.%d")
REPO_BRANCH_VERSION ?= 0

# Author's information
AUTHOR_WEBSITE      ?= none
AUTHOR_EMAIL        ?= none

# If needed, declare the minimum NML requirements
REQUIRED_NML_BRANCH  = 0.4
# MIN_NML_REVISION   = 0
